name: 'Sync issues with Jira'
description: 'Create or update Jira issues to match open issues in this repo'
runs:
  using: 'node20'
  main: 'jira.js'
inputs:
  github-token:
    description: "Token to use for accessing GitHub's API. Usually secrets.GITHUB_TOKEN"
    required: true
  jira-auth:
    description: "Basic auth string for accessing Jira's cloud v3 API. Of the form, username:token"  
    required: true
  include-issue:
    description: 'Number of an issue to include even if it is closed'
    required: false

