name: sync issues with Jira
on:
  issues:
    types: [opened, closed, reopened, edited]
jobs:
  sync-and-process-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sync tool
        uses: actions/checkout@v3
        with:
          lfs: true
          sparse-checkout: |
            .github
            tools
      
      - name: setup node
        uses: actions/setup-node@v4

      - name: install dependencies
        run: npm --prefix ./tools/automation/actions/jira-sync ci

      - name: sync issues
        uses: ./tools/automation/actions/jira-sync
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-auth: ${{ secrets.JIRA_AUTH }}
          include-issue: ${{ github.event.issue.number }}
